services:
  db:
    image: mysql
    restart: always
    volumes:
      - db_data:/var/lib/mysql
      - .:/app
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "3306:3306"
      
  app: 
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    env_file:
      - .env
    volumes: 
      - ".:/app"
    ports: 
      - "3000:3000"
    depends_on:
      - db
    links:
      - db
    stdin_open: true
    tty: true
volumes:
  db_data:

# RUN THIS COMMAND FIRST TO INIT RAILS PROJECT: docker-compose run app rails new . --force --database=mysql --skip-bundle

# sudo chown -R $USER .

# CHANGE CONTENT database.yml file:
# username: <%= ENV["DATABASE_USER"] %>
# password: <%= ENV["DATABASE_PASSWORD"] %>
# host: <%= ENV["DATABASE_HOST"] %>

# docker-compose build

# RUN THIS COMMAND BELOW TO INIT MYSQL DB
# docker-compose run app rake db:create
# docker-compose run app rake db:migrate
# docker-compose run app rake db:seed

# docker-compose up